<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");?>

<?$APPLICATION->IncludeComponent(
    "bitrix:sale.basket.basket",
    "new",
    array(
        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
        "COLUMNS_LIST" => array(
            0 => "NAME",
            1 => "DISCOUNT",
            2 => "PROPS",
            3 => "DELETE",
            4 => "DELAY",
            5 => "PRICE",
            6 => "QUANTITY",
            7 => "SUM",
        ),
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "PATH_TO_ORDER" => "/cart/",
        "HIDE_COUPON" => "N",
        "QUANTITY_FLOAT" => "N",
        "PRICE_VAT_SHOW_VALUE" => "Y",
        "TEMPLATE_THEME" => "site",
        "SET_TITLE" => "Y",
        "AJAX_OPTION_ADDITIONAL" => "",
        "OFFERS_PROPS" => array(
            0 => "CML2_ARTICLE",
        ),
        "COMPONENT_TEMPLATE" => "new",
        "USE_PREPAYMENT" => "N",
        "AUTO_CALCULATION" => "Y",
        "ACTION_VARIABLE" => "basketAction",
        "USE_GIFTS" => "Y",
        "GIFTS_PLACE" => "BOTTOM",
        "GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
        "GIFTS_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_TEXT_LABEL_GIFT" => "Подарок",
        "GIFTS_PRODUCT_QUANTITY_VARIABLE" => "",
        "GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
        "GIFTS_SHOW_OLD_PRICE" => "N",
        "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
        "GIFTS_SHOW_NAME" => "Y",
        "GIFTS_SHOW_IMAGE" => "Y",
        "GIFTS_MESS_BTN_BUY" => "Выбрать",
        "GIFTS_MESS_BTN_DETAIL" => "Подробнее",
        "GIFTS_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_CONVERT_CURRENCY" => "Y",
        "GIFTS_HIDE_NOT_AVAILABLE" => "N"
    ),
    false
);?>
